// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjglbR5FVFmZPx4vKTN_QFhB9pJACnd_4',
    appId: '1:884100241599:web:82fea5745ea6ffe4678e0a',
    messagingSenderId: '884100241599',
    projectId: 'tweetz-8b4e8',
    authDomain: 'tweetz-8b4e8.firebaseapp.com',
    storageBucket: 'tweetz-8b4e8.firebasestorage.app',
    measurementId: 'G-36H7QHM2VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAqb8NRifP1AX88TnED2EHsnGEi8hfecc',
    appId: '1:884100241599:android:f8cdaed6bbeed1dc678e0a',
    messagingSenderId: '884100241599',
    projectId: 'tweetz-8b4e8',
    storageBucket: 'tweetz-8b4e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7P7_EaV-FDAZqE1vXDv663mwbMz6QNes',
    appId: '1:884100241599:ios:8b237212fda69f4c678e0a',
    messagingSenderId: '884100241599',
    projectId: 'tweetz-8b4e8',
    storageBucket: 'tweetz-8b4e8.firebasestorage.app',
    iosBundleId: 'com.example.tweetsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7P7_EaV-FDAZqE1vXDv663mwbMz6QNes',
    appId: '1:884100241599:ios:8b237212fda69f4c678e0a',
    messagingSenderId: '884100241599',
    projectId: 'tweetz-8b4e8',
    storageBucket: 'tweetz-8b4e8.firebasestorage.app',
    iosBundleId: 'com.example.tweetsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjglbR5FVFmZPx4vKTN_QFhB9pJACnd_4',
    appId: '1:884100241599:web:fdac1446dc865c0a678e0a',
    messagingSenderId: '884100241599',
    projectId: 'tweetz-8b4e8',
    authDomain: 'tweetz-8b4e8.firebaseapp.com',
    storageBucket: 'tweetz-8b4e8.firebasestorage.app',
    measurementId: 'G-TM3HH2P9RN',
  );
}
